{% set name = "orca" %}
{% set version = "4.1.1" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4819f07c570e8a9c0ad0508c9466b4354d20b0434c387e576274fa6bce2ca85c

build:
  number: 1
  binary_relocation: false
  skip: true  # [linux]

requirements:
  build:
    - nodejs

test:
  commands:
    - orca --help

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
