{% set name = "orca" %}
{% set version = "4.1.3" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 876d322e7e43dbcd5810c88d74d3eb9c5f7fa9202a133dbaafbc99f06c991ef6

build:
  number: 0
  binary_relocation: false
  skip: true  # [linux]

requirements:
  build:
    - nodejs

test:
  commands:
    - orca --help

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
