{% set name = "orca" %}
{% set version = "3.4.3" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 35d5d5a03070753b00b4c6bf0ed5dfe056738f1e5e40597b56033f44ecf40665

build:
  number: 1
  binary_relocation: false
  skip: true  # [linux]

requirements:
  build:
    - nodejs

test:
  commands:
    - orca --help

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - rluria14
    - oblute
