{% set name = "orca" %}
{% set version = "3.3.5" %}

package:
  name: plotly-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/plotly/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f58318dc3c5860c57627a43ea78d8cafa8dee0571200cbc661fcbdceaf6b8794

build:
  number: 0
  noarch: generic
  script:
    - npm install -g orca

requirements:
  build:
    - nodejs
  run:
    - nodejs

test:
  commands:
    - npm list -g orca
  requires:
    - nodejs

about:
  home: https://github.com/plotly/orca
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line application for generating static images of interactive plotly charts.
  doc_url: https://github.com/plotly/orca/
  dev_url: https://github.com/plotly/orca/

extra:
  recipe-maintainers:
    - rluria14
    - oblute
